### ISSUE TITLE
404 file note found when clicking 'add plug-in' from insert menu

### ISSUE THREAD

**Issue by richstep** [OpenLiveWriter/OpenLiveWriter.Github.io#85] opened 2017-04-28 17:08 UTC
http://openlivewriter.org/WriterRedirect/WriterDownloadPluginsURL/%7B

**Comment by ScottIsAFool** [comment] 2017-04-29 14:06
Closing as duplicate of #84

**Closed by ScottIsAFool** 2017-04-29 14:06 UTC
